### ISSUE TITLE
How to handle different configurations

### ISSUE THREAD

**Issue by gianluca-sabena** [unicredit/react-boilerplate#2]
How can I have 2 configuration files, one to use in dev mode and another one to use when  building the application?

**Comment by andreaferretti** [comment]
I think the best way would be as follows: have a `config` module, that in turn imports and merges two other modules, such as `config-shared` and `config-local`. The first one is committed on git, while the second one is in .gitignore and can be customized on each installation.

This allows, for instance, to have secrets only available on build machines

**Comment by fabiofumarola** [comment]
I suggest to integrate [Konky](https://github.com/creynders/konfy)

**Comment by fabiofumarola** [comment]
closed with tag 1.4.1
